# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default=b'', max_length=500)),
                ('score_result', models.PositiveIntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExamLibItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[(b'choice', b'Choice'), (b'answer', b'Answer')], max_length=45)),
                ('a', models.TextField(blank=True, max_length=500)),
                ('b', models.TextField(blank=True, max_length=500)),
                ('c', models.TextField(blank=True, max_length=500)),
                ('d', models.TextField(blank=True, max_length=500)),
                ('score', models.PositiveIntegerField()),
                ('ref_answer', models.TextField(max_length=500, verbose_name=b'ref_answer')),
                ('category', models.CharField(choices=[(b'ip', b'IP'), (b'linux', b'Linux'), (b'lte', b'LTE'), (b'python', b'Python'), (b'robot', b'Robot'), (b'test', b'Test'), (b'log', b'LOG')], max_length=45)),
                ('source', models.CharField(blank=True, max_length=120, null=True)),
                ('contributor', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name=b'Paper Name')),
                ('type', models.CharField(choices=[(b'a', b'A'), (b'b', b'B'), (b'c', b'C'), (b'd', b'D')], max_length=45, verbose_name=b'Paper Type')),
                ('total_score', models.IntegerField()),
                ('examlibitem', models.ManyToManyField(blank=True, to='exam.ExamLibItem', verbose_name=b'Exam Library Item')),
            ],
        ),
        migrations.AddField(
            model_name='examresult',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Paper'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examitem',
            name='exam_result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.ExamResult'),
        ),
        migrations.AddField(
            model_name='examitem',
            name='examlibitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamLibItem'),
        ),
        migrations.AddField(
            model_name='examitem',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Paper'),
        ),
        migrations.AddField(
            model_name='examitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
