# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examlibitem',
            name='category',
            field=models.CharField(choices=[(b'ip', b'IP'), (b'linux', b'Linux'), (b'lte', b'LTE'), (b'python', b'Python'), (b'cpp', b'C++'), (b'robot', b'Robot'), (b'test', b'Test'), (b'log', b'LOG')], max_length=45),
        ),
        migrations.AlterField(
            model_name='examlibitem',
            name='content',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
