# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20180918_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examitem',
            name='score_result',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
