# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(default=b'', max_length=120)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('book', models.CharField(choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etymon', models.CharField(max_length=45)),
                ('relation', models.CharField(choices=[(b'Self', b'Self'), (b'synonym', b'Synonym'), (b'antonym', b'Antonym'), (b'homograph', b'Homograph'), (b'etymon', b'etymon')], max_length=120)),
                ('exampleWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engdict.ExampleWord')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phonetic', models.CharField(max_length=45)),
                ('explain', models.TextField(blank=True, default=b'', max_length=120, null=True)),
                ('progress', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField(blank=True, null=True)),
                ('book', models.CharField(choices=[(b'youdao', b'YOUDAO')], max_length=120)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engdict.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phonetic', models.CharField(max_length=45)),
                ('explain', models.CharField(default=b'', max_length=120)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('book', models.CharField(choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days')], max_length=120)),
                ('relation', models.CharField(choices=[(b'Self', b'Self'), (b'synonym', b'Synonym'), (b'antonym', b'Antonym'), (b'homograph', b'Homograph'), (b'etymon', b'etymon')], default=b'Self', max_length=120)),
                ('etymon', models.CharField(blank=True, max_length=45, null=True)),
                ('word', models.ManyToManyField(blank=True, to='engdict.Word')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='exampleword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engdict.Word'),
        ),
    ]
