# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0002_auto_20180928_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='in_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exampleword',
            name='book',
            field=models.CharField(choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days'), (b'IELTS', b'IELTS'), (b'BSWX', b'BSWX'), (b'YOUDAO', b'YOUDAO')], max_length=120),
        ),
        migrations.AlterField(
            model_name='worddict',
            name='book',
            field=models.CharField(choices=[(b'youdao', b'YOUDAO'), (b'kingsoft', b'kingsoft')], max_length=120),
        ),
        migrations.AlterField(
            model_name='wordexp',
            name='book',
            field=models.CharField(choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days'), (b'IELTS', b'IELTS'), (b'BSWX', b'BSWX'), (b'YOUDAO', b'YOUDAO')], max_length=120),
        ),
        migrations.AddField(
            model_name='tag',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='category',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, to='engdict.Word'),
        ),
    ]
