# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0004_auto_20181002_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordexp',
            name='antonymy',
            field=models.ManyToManyField(blank=True, related_name='antonymy', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='wordexp',
            name='etyma',
            field=models.ManyToManyField(blank=True, related_name='etyma', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='wordexp',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='wordexp',
            name='resemblance',
            field=models.ManyToManyField(blank=True, related_name='resemblance', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='wordexp',
            name='semantic',
            field=models.ManyToManyField(blank=True, related_name='semantic', to='engdict.Word'),
        ),
        migrations.AlterField(
            model_name='wordexp',
            name='word',
            field=models.ManyToManyField(blank=True, related_name='word', to='engdict.Word'),
        ),
    ]
