# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0005_auto_20181003_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='linked_word',
            field=models.ManyToManyField(blank=True, related_name='related_word', to='engdict.Word'),
        ),
    ]
