# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0007_auto_20181004_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='linked_word',
            field=models.ManyToManyField(blank=True, to='engdict.Word'),
        ),
    ]
