# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0010_auto_20181014_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
    ]
