# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0012_word_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='engdict.Word'),
        ),
        migrations.AlterField(
            model_name='exampleword',
            name='book',
            field=models.CharField(choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'life', b'LIFE'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days'), (b'IELTS', b'IELTS'), (b'BSWX', b'BSWX'), (b'YOUDAO', b'YOUDAO'), (b'other', b'Other')], max_length=120),
        ),
        migrations.AlterField(
            model_name='word',
            name='book',
            field=models.CharField(blank=True, choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'life', b'LIFE'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days'), (b'IELTS', b'IELTS'), (b'BSWX', b'BSWX'), (b'YOUDAO', b'YOUDAO'), (b'other', b'Other')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='wordexp',
            name='book',
            field=models.CharField(choices=[(b'nce3', b'NCE3'), (b'nce4', b'NCE4'), (b'bbc', b'BBC'), (b'voa', b'VOA'), (b'cctvnews', b'CCTVNEWS'), (b'mail', b'MAIL'), (b'life', b'LIFE'), (b'20000', b'20000'), (b'22000', b'22000'), (b'100days', b'100days'), (b'IELTS', b'IELTS'), (b'BSWX', b'BSWX'), (b'YOUDAO', b'YOUDAO'), (b'other', b'Other')], max_length=120),
        ),
    ]
