# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0013_auto_20181015_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='engdict.Word'),
        ),
    ]
