# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0015_auto_20181016_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddict',
            name='book',
            field=models.CharField(choices=[(b'youdao', b'YOUDAO'), (b'kingsoft', b'kingsoft')], default=b'youdao', max_length=120),
        ),
    ]
