# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0016_auto_20181017_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonymy_word',
            field=models.ManyToManyField(blank=True, related_name='antonymy_word_reverse', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='etyma_word',
            field=models.ManyToManyField(blank=True, related_name='etyma_word_reverse', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='resemblance_word',
            field=models.ManyToManyField(blank=True, related_name='resemblance_word_reverse', to='engdict.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='semantic_word',
            field=models.ManyToManyField(blank=True, related_name='semantic_word_reverse', to='engdict.Word'),
        ),
    ]
