# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0018_auto_20190818_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='antonymy_word',
            field=models.ManyToManyField(blank=True, null=True, related_name='antonymy_word_reverse', to='engdict.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='etyma_word',
            field=models.ManyToManyField(blank=True, null=True, related_name='etyma_word_reverse', to='engdict.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='explain',
            field=models.TextField(blank=True, default=b'', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='resemblance_word',
            field=models.ManyToManyField(blank=True, null=True, related_name='resemblance_word_reverse', to='engdict.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='semantic_word',
            field=models.ManyToManyField(blank=True, null=True, related_name='semantic_word_reverse', to='engdict.Word'),
        ),
    ]
