# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-13 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engdict', '0020_auto_20190818_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
