name: iexam
version: 1

libraries:
- name: "django"
  version: "1.8.4"

- name: "django-crispy-forms"
  version: "1.6.0"

- name: "django-registration-redux"
  version: "1.4"

- name: "gunicorn"
  version: "19.4.5"

- name: "psycopg2"
  version: "2.6.1"

- name: "dj-database-url"
  version: "0.3.0" 